apiVersion: agent.open-cluster-management.io/v1beta1
kind: KlusterletConfig
metadata:
  name: mycluster
  namespace: mycluster
spec:
  clusterName: mycluster
  clusterNamespace: mycluster
  bootstrapConfig:
    hubSecret: multicluster-endpoint/klusterlet-bootstrap
  applicationManager:
    enabled: true
  clusterLabels:
    cloud: auto-detect
    vendor: auto-detect
  connectionManager:
    enabledGlobalView: false
  imageRegistry: quay.io/open-cluster-management
  imagePullSecret: multiclusterhub-operator-pull-secret
  policyController:
    enabled: true
  prometheusIntegration:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  cisController:
    enabled: true
  iamPolicyController:
    enabled: true
  version: 1.0.0
