apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"controller-tools.k8s.io":"1.0"},"name":"selectorsyncsets.hive.openshift.io"},"spec":{"group":"hive.openshift.io","names":{"kind":"SelectorSyncSet","plural":"selectorsyncsets","shortNames":["sss"]},"scope":"Cluster","validation":{"openAPIV3Schema":{"properties":{"apiVersion":{"description":"APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources","type":"string"},"kind":{"description":"Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds","type":"string"},"metadata":{"type":"object"},"spec":{"properties":{"clusterDeploymentSelector":{"description":"ClusterDeploymentSelector is a LabelSelector indicating which clusters the SelectorSyncSet applies to in any namespace.","type":"object"},"patches":{"description":"Patches is the list of patches to apply.","items":{"properties":{"apiVersion":{"description":"APIVersion is the Group and Version of the object to be patched.","type":"string"},"applyMode":{"description":"ApplyMode indicates if the patch apply mode is \"AlwaysApply\" (default) or \"ApplyOnce\". ApplyMode \"AlwaysApply\" indicates that the patch should be applied every time reconciliation occurs. ApplyMode \"ApplyOnce\" indicates that the patch should only be applied once.","type":"string"},"kind":{"description":"Kind is the Kind of the object to be patched.","type":"string"},"name":{"description":"Name is the name of the object to be patched.","type":"string"},"namespace":{"description":"Namespace is the Namespace in which the object to patch exists. Defaults to the SyncSet's Namespace.","type":"string"},"patch":{"description":"Patch is the patch to apply.","type":"string"},"patchType":{"description":"PatchType indicates the PatchType as \"strategic\" (default), \"json\", or \"merge\".","type":"string"}},"type":"object"},"type":"array"},"resourceApplyMode":{"description":"ResourceApplyMode indicates if the Resource apply mode is \"upsert\" (default) or \"sync\". ApplyMode \"upsert\" indicates create and update. ApplyMode \"sync\" indicates create, update and delete.","type":"string"},"resources":{"description":"Resources is the list of objects to sync from RawExtension definitions.","items":{"type":"object"},"type":"array"},"secretReferences":{"description":"SecretReferences is the list of secrets to sync from existing resources.","items":{"properties":{"source":{"type":"object"},"target":{"type":"object"}},"type":"object"},"type":"array"}},"type":"object"},"status":{"type":"object"}}}},"version":"v1"},"status":{"acceptedNames":{"kind":"","plural":""},"conditions":[],"storedVersions":[]}}
  creationTimestamp: "2019-11-13T16:20:15Z"
  generation: 1
  labels:
    controller-tools.k8s.io: "1.0"
  name: selectorsyncsets.hive.openshift.io
  resourceVersion: "304637"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/selectorsyncsets.hive.openshift.io
  uid: 798ed0ec-0631-11ea-b161-025a1e91c929
spec:
  conversion:
    strategy: None
  group: hive.openshift.io
  names:
    kind: SelectorSyncSet
    listKind: SelectorSyncSetList
    plural: selectorsyncsets
    shortNames:
    - sss
    singular: selectorsyncset
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            clusterDeploymentSelector:
              description: ClusterDeploymentSelector is a LabelSelector indicating
                which clusters the SelectorSyncSet applies to in any namespace.
              type: object
            patches:
              description: Patches is the list of patches to apply.
              items:
                properties:
                  apiVersion:
                    description: APIVersion is the Group and Version of the object
                      to be patched.
                    type: string
                  applyMode:
                    description: ApplyMode indicates if the patch apply mode is "AlwaysApply"
                      (default) or "ApplyOnce". ApplyMode "AlwaysApply" indicates
                      that the patch should be applied every time reconciliation occurs.
                      ApplyMode "ApplyOnce" indicates that the patch should only be
                      applied once.
                    type: string
                  kind:
                    description: Kind is the Kind of the object to be patched.
                    type: string
                  name:
                    description: Name is the name of the object to be patched.
                    type: string
                  namespace:
                    description: Namespace is the Namespace in which the object to
                      patch exists. Defaults to the SyncSet's Namespace.
                    type: string
                  patch:
                    description: Patch is the patch to apply.
                    type: string
                  patchType:
                    description: PatchType indicates the PatchType as "strategic"
                      (default), "json", or "merge".
                    type: string
                type: object
              type: array
            resourceApplyMode:
              description: ResourceApplyMode indicates if the Resource apply mode
                is "upsert" (default) or "sync". ApplyMode "upsert" indicates create
                and update. ApplyMode "sync" indicates create, update and delete.
              type: string
            resources:
              description: Resources is the list of objects to sync from RawExtension
                definitions.
              items:
                type: object
              type: array
            secretReferences:
              description: SecretReferences is the list of secrets to sync from existing
                resources.
              items:
                properties:
                  source:
                    type: object
                  target:
                    type: object
                type: object
              type: array
          type: object
        status:
          type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: SelectorSyncSet
    listKind: SelectorSyncSetList
    plural: selectorsyncsets
    shortNames:
    - sss
    singular: selectorsyncset
  conditions:
  - lastTransitionTime: "2019-11-13T16:20:15Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: null
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1
