apiVersion: apps/v1
kind: Deployment
metadata:
  name: rcm-controller
  namespace: open-cluster-management
  labels:
    app: rcm-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rcm-controller
  template:
    metadata:
      labels:
        name: rcm-controller
    spec:
      serviceAccountName: rcm-controller
      containers:
        - name: rcm-controller
          image: quay.io/open-cluster-management/rcm-controller:latest
          command:
          - rcm-controller
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "rcm-controller"
            - name: DEFAULT_IMAGE_PULL_SECRET
              value: multiclusterhub-operator-pull-secret
            - name: DEFAULT_IMAGE_REGISTRY
              value: quay.io/open-cluster-management
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
