kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: multicloud-operators-cluster-controller
subjects:
- kind: ServiceAccount
  name: multicloud-operators-cluster-controller
  namespace: multicloud-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
