kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rcm-controller
subjects:
- kind: ServiceAccount
  name: rcm-controller
  namespace: open-cluster-management
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
