apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: managedcluster-import-controller
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - klusterlets
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - serviceaccounts
  - namespaces
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - managedcluster-import-controller
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
- apiGroups:
  - multicloud.ibm.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  resources:
  - infrastructures
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - clusterregistry.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - hive.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - mcm.ibm.com
  resources:
  - '*'
  verbs:
  - '*'